"""
stage2/models/completion_dit.py
================================
Stage 2 for Strategy B1: scene completion via inpainting.

CompletionDiT denoises unobserved geometry tokens conditioned on z_layout,
which comes from Stage 1's deterministic Layout16Projector.

Architecture
------------
    Z_masked [B, 512, 32]   — observed tokens clean, unobserved = noise
    z_layout [B,  16, 32]   — deterministic layout conditioning (K/V per layer)
    obs_mask [B, 512]       — 1 = observed (held fixed), 0 = unobserved (denoise)

        ↓  token_embedder
    [B, 512, hidden_size]   — observed positions: embedded tokens
                            — unobserved positions: learned mask_token
        ↓  + pos_embed
    N × CrossAttnDiTBlock   — z_layout as cross-attention K/V per layer
        ↓  TokenFinalLayer
    [B, 512, 32]            — velocity prediction

Loss is computed only on unobserved token positions (obs_mask == 0).

Training
--------
During training, obs_mask is generated by randomly masking 30–80% of the
voxel tokens to simulate partial scans at varying coverage levels.
At inference, obs_mask comes from the actual partial scan provided by the user.

Why B1 is ideal for completion
-------------------------------
Layout16Projector is deterministic: the same partial scan always produces
exactly the same z_layout (cos_sim = 1.000 at 40% coverage).  There is no
sampling noise in the conditioning signal, so the DiT always receives a
stable, accurate scene-type descriptor even from limited observation.
"""

import random
import torch
import torch.nn as nn
import torch.nn.functional as F
from ..external.dit_block import (
    modulate, Mlp,
    TimestepEmbedder, TokenFinalLayer, init_dit_weights,
)
from .geometry_dit import CrossAttnDiTBlock

# ── Constants matching Stage 1 ─────────────────────────────────────────────
N_Z       = 512   # full geometry latent tokens
N_LAYOUT  = 16    # z_layout tokens from Layout16Projector
TOKEN_DIM = 32    # embed_dim from Stage 1


# ============================================================================
# CompletionDiT
# ============================================================================

class CompletionDiT(nn.Module):
    """
    Inpainting DiT for Strategy B1 scene completion.

    Parameters
    ----------
    hidden_size : int    (default 384)
    depth       : int    (default 12)
    num_heads   : int    (default 12)
    mlp_ratio   : float  (default 4.0)

    forward(x, t, z_layout, obs_mask) → [B, 512, 32]
    """

    def __init__(
        self,
        hidden_size: int   = 384,
        depth:       int   = 12,
        num_heads:   int   = 12,
        mlp_ratio:   float = 4.0,
    ):
        super().__init__()
        self.hidden_size = hidden_size

        # Token input projection
        self.token_embedder  = nn.Linear(TOKEN_DIM, hidden_size)
        # Learnable mask token for unobserved positions
        self.mask_token      = nn.Parameter(torch.zeros(1, 1, hidden_size))
        nn.init.trunc_normal_(self.mask_token, std=0.02)

        # Layout conditioning: z_layout [B, 16, 32] → [B, 16, hidden_size]
        self.layout_embedder = nn.Linear(TOKEN_DIM, hidden_size)

        self.t_embedder = TimestepEmbedder(hidden_size)

        # Learned PE over 512 positions
        self.pos_embed = nn.Parameter(torch.zeros(1, N_Z, hidden_size))
        nn.init.trunc_normal_(self.pos_embed, std=0.02)

        # CrossAttnDiTBlock: z_layout as K/V per layer (mirrors B1 VAE decoder)
        self.blocks = nn.ModuleList([
            CrossAttnDiTBlock(hidden_size, num_heads, mlp_ratio=mlp_ratio)
            for _ in range(depth)
        ])

        self.final_layer = TokenFinalLayer(hidden_size, TOKEN_DIM)

        init_dit_weights(self)

    # ── Forward ────────────────────────────────────────────────────────────

    def forward(
        self,
        x:        torch.Tensor,
        t:        torch.Tensor,
        z_layout: torch.Tensor,
        obs_mask: torch.Tensor,
    ) -> torch.Tensor:
        """
        x        : [B, 512, 32]  noisy tokens (observed=clean, unobserved=noise)
        t        : [B]           timestep ∈ [0, 1]
        z_layout : [B,  16, 32]  deterministic layout conditioning
        obs_mask : [B, 512]      float32 — 1=observed (fix), 0=unobserved (denoise)

        Returns  : [B, 512, 32]  velocity prediction
                   (only unobserved positions are meaningful for the loss)
        """
        # Replace unobserved positions with mask_token before embedding
        h   = self.token_embedder(x)                     # [B, 512, D]
        msk = obs_mask.unsqueeze(-1).float()             # [B, 512, 1]
        h   = h * msk + self.mask_token * (1.0 - msk)   # masked positions → mask_token
        h   = h + self.pos_embed                         # [B, 512, D]

        ctx = self.layout_embedder(z_layout)             # [B, 16, D]
        c   = self.t_embedder(t)                         # [B, D]

        for block in self.blocks:
            h = block(h, c, ctx)

        return self.final_layer(h, c)                    # [B, 512, 32]

    # ── Convenience ────────────────────────────────────────────────────────

    def num_params(self) -> int:
        return sum(p.numel() for p in self.parameters())

    def __repr__(self) -> str:
        return (
            f"CompletionDiT(hidden={self.hidden_size}, "
            f"depth={len(self.blocks)}, "
            f"params={self.num_params()/1e6:.2f}M)"
        )


# ============================================================================
# Masking utilities
# ============================================================================

def sample_voxel_mask(
    B:               int,
    n_tokens:        int = N_Z,
    device:          torch.device = None,
    coverage_range:  tuple = (0.3, 0.8),
) -> torch.Tensor:
    """
    Generate a random binary mask simulating partial scan coverage.

    Each batch element independently draws a coverage fraction from
    coverage_range and marks that fraction of tokens as observed (1).

    Returns
    -------
    obs_mask : [B, n_tokens]  float32, 1=observed, 0=unobserved
    """
    masks = []
    for _ in range(B):
        cov    = random.uniform(*coverage_range)
        n_obs  = int(n_tokens * cov)
        perm   = torch.randperm(n_tokens, device=device)
        mask   = torch.zeros(n_tokens, device=device)
        mask[perm[:n_obs]] = 1.0
        masks.append(mask)
    return torch.stack(masks)   # [B, n_tokens]


def completion_training_step(
    model:    "CompletionDiT",
    z_clean:  torch.Tensor,
    z_layout: torch.Tensor,
    path_sampler,
) -> torch.Tensor:
    """
    One training step for CompletionDiT.

    Unlike the standard Transport.training_losses() call (which applies noise
    uniformly to all tokens), completion training:
      1. Randomly masks 30–80% of tokens as 'observed' (held fixed)
      2. Applies flow matching noise only to 'unobserved' tokens
      3. Computes the MSE loss only on unobserved token positions

    Parameters
    ----------
    model        : CompletionDiT
    z_clean      : [B, 512, 32]  clean Stage 1 latents (from encoder mode)
    z_layout     : [B,  16, 32]  deterministic layout tokens
    path_sampler : ICPlan (or VPCPlan/GVPCPlan) — from Transport.path_sampler

    Returns
    -------
    loss : scalar tensor
    """
    B      = z_clean.shape[0]
    device = z_clean.device

    # ── 1. Sample mask ──────────────────────────────────────────────────────
    obs_mask     = sample_voxel_mask(B, N_Z, device)            # [B, 512]
    mask_exp     = obs_mask.unsqueeze(-1)                       # [B, 512, 1]

    # ── 2. Sample t and noise ───────────────────────────────────────────────
    t    = torch.rand(B, device=device)                         # [B]
    z0   = torch.randn_like(z_clean)                            # pure noise

    # ── 3. Compute x_t: linear interpolation on unobserved; clean on observed
    t_exp = t.view(B, 1, 1)
    z_t   = t_exp * z_clean + (1.0 - t_exp) * z0               # [B, 512, 32]
    z_t   = z_t * (1.0 - mask_exp) + z_clean * mask_exp        # observed = clean

    # ── 4. Velocity target (only for unobserved tokens) ────────────────────
    v_target = z_clean - z0                                     # [B, 512, 32]

    # ── 5. Model prediction ─────────────────────────────────────────────────
    v_pred = model(z_t, t, z_layout, obs_mask)                  # [B, 512, 32]

    # ── 6. Loss on unobserved positions only ────────────────────────────────
    loss = ((v_pred - v_target) ** 2 * (1.0 - mask_exp)).sum()
    loss = loss / ((1.0 - mask_exp).sum() + 1e-8)
    return loss


# ── Size presets ─────────────────────────────────────────────────────────────

def CompletionDiT_S(**kw):  return CompletionDiT(hidden_size=256, depth=8,  num_heads=8,  **kw)
def CompletionDiT_B(**kw):  return CompletionDiT(hidden_size=384, depth=12, num_heads=12, **kw)  # default
def CompletionDiT_L(**kw):  return CompletionDiT(hidden_size=512, depth=16, num_heads=16, **kw)

CompletionDiT_models = {
    "CompletionDiT-S": CompletionDiT_S,
    "CompletionDiT-B": CompletionDiT_B,
    "CompletionDiT-L": CompletionDiT_L,
}