compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
mixed_precision: 'no'
num_machines: 1
num_processes: 4        # number of H100s per node — adjust to match --gpus in job script
use_cpu: false